import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  fields: [
    defineField({ name: "whatsappNumber", title: "WhatsApp number", type: "string" }),
    defineField({
      name: "announcementEnabled",
      title: "Show announcement bar",
      type: "boolean",
      description: "Turns on the thin announcement message at the very top of the website.",
      initialValue: false,
    }),
    defineField({
      name: "announcementText",
      title: "Announcement text",
      type: "string",
      description: "Short message shown in the top announcement bar.",
    }),
    defineField({
      name: "announcementHref",
      title: "Announcement link",
      type: "string",
      description: "Optional URL. Leave empty for plain text.",
    }),
    defineField({ name: "bankName", title: "Bank name", type: "string" }),
    defineField({ name: "bankAccountName", title: "Bank account name", type: "string" }),
    defineField({ name: "bankAccountNumber", title: "Bank account number", type: "string" }),
    defineField({ name: "bankBranch", title: "Bank branch", type: "string" }),
    defineField({
      name: "customSizeCharge",
      title: "Custom size charge",
      type: "number",
      description: "Extra amount added when a customer chooses custom sizing.",
      initialValue: 1500,
    }),
    defineField({
      name: "customSizeDispatchDays",
      title: "Custom size dispatch days",
      type: "number",
      initialValue: 14,
    }),
    defineField({
      name: "bankTransferDeadlineDays",
      title: "Bank transfer deadline days",
      type: "number",
      description: "How many days the customer has to upload/send the bank transfer slip.",
      initialValue: 3,
    }),
    defineField({
      name: "shippingBaseFee",
      title: "Shipping base fee",
      type: "number",
      description: "Baseline delivery charge for the first billable kilogram.",
      initialValue: 1500,
    }),
    defineField({
      name: "shippingProductWeightGrams",
      title: "Weight per product (grams)",
      type: "number",
      description: "Used for checkout shipping. Default is 700g per product.",
      initialValue: 700,
    }),
    defineField({
      name: "shippingExtraFeePerKg",
      title: "Extra shipping fee per kg",
      type: "number",
      description: "Amount added for every billable kilogram after the first kilogram.",
      initialValue: 100,
    }),
    defineField({
      name: "shippingRoundingGraceGrams",
      title: "Shipping rounding grace (grams)",
      type: "number",
      description: "Small weight allowance before charging the next kg. Default 100g makes 2.1kg bill as 2kg.",
      initialValue: 100,
    }),
    defineField({
      name: "isStoreLocatorActive",
      title: "Enable Store Locator",
      type: "boolean",
      description: "Enable this to show the Store Locator page, footer links, and out-of-stock size popups on the website. Turn off to hide them.",
      initialValue: false,
    }),
  ],
});
